# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  database: clutch_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: clutch_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: clutch_production
  pool: 5
  timeout: 5000
